<!--
The {#rmd-basics} text after the chapter declaration will allow us to link throughout the document back to the beginning of Chapter 1.  These labels will automatically be generated (if not specified) by changing the spaces to hyphens and capital letters to lowercase.  Look for the reference to this label at the beginning of Chapter 2.
-->

# Working environment {#workenv}

## Applications and tools

Working in development field often imposes to be methodic. In particular for bug tracking or code versioning to detect errors and keep an history of code modifications. Being methodic is also important for code readability (adding comments for example) and code reproducibility. For the reason that the AGROMET project is public, this last point is important for transparency.

That's why preparing the working environment is important to help achieve these good practices.

&nbsp;

First, I have installed **Ubuntu GNOME**, a distribution of Linux on my laptop. Indeed, this is an open-source OS prefered by developers. It has a large community which is important to solve problems and bugs and to improve the OS. Because it is free, anyone can install it and that is important for reproducibility. Due to its large community of developers, Linux is safer because they monitor for issues and can repair them. Moreover, Linux has only 3% of the market and hackers prefer target a large segment of users as Windows. This installation of Ubuntu was done thanks to a USB drive with a boot of Ubuntu GNOME.

&nbsp;

Once I had Ubuntu installed on my laptop, I used an **ANSIBLE script** to automatically install all the applications I need. Moreover, this script handles the updates of these applications. That is a very useful way to earn some time and it helps science reproductibility because anyone with the script will end up with the exact same installation.

&nbsp;

<!-- source : https://openclassrooms.com/en/courses/1197906-securiser-son-serveur-linux -->
Accessing to servers has to be secured to be protected against intrusions and monitor logs. That's why every developer should have a **SSH** key. This key or token is unique and enable people to access to servers. It is useful to access to Git repositories for example. It also helps to save some time because anyone who wants to connect a service does not need to provide a login and password each time using an SSH connection instead.

**GitHub** is a hosting service for version control. It facilitates the collaborative work on a same code, the handle of code versions and the use of code developed by other users. It is a very common tool for developers because it ensures a public and online access.

For my internship, I had to collaboratively work on code development with my mentor. This is why we have been using GitHub. For each of the code folders that I had to work on, I made a fork that I've downloaded on my laptop for further local developments. Then, I have a copy that I can modify and I can send my modifications on GitHub. To clone these repositories, my SSH key was useful.

&nbsp;

The current development version of the AGROMET platform already offers an **API** that allows to retrieve weather data from the stations. A specific API token with reading rights has been created for my internship. The API provides data in both JSON and GeoJSON formats which are open-standard file formats. These formats are easy to parse by machines and are easy to read by humans.

&nbsp;

**Docker** is a software for containerize platforms. This container approach has many advantages compares to the use of virtual machines : lightweight, quick and modular.

There are two main reasons to use R in conjunction with Docker. First, it allows you to quickly and easily share your work whatever the OS and R configuration of your collaborators. Second, it allows you to work in an isolated environment. This means that you will never pollute your OS and e.g. run in time-consuming re-installation procedures due to broken configuration. In case of OS crash, simply relaunch your Docker R container with a single command and you are ready to work.

## Reproducible science

Reproducible science refers to the idea that full working environment of a research can be used by anyone to reproduce the results and create a new work based on it. That ensures reliability and credibility because the entire work is available.

&nbsp;

In the case of the AGROMET project, the purpose of choosing open-source is to allow reproducible science and transparency about the chosen methods and therefore the meaning of the produced datasets.

Transparency is promoted thanks to open science. That means the content and the results of the project will be accessible to others. Indeed, transparency is superior to trust and is an ideal (Munafo, 2017).

Development represents the major part of the project. Today, open science is widely used and tools have been developed for that. The availability of code on GitHub ensures that anyone can check the code and inspect it. Then, some people can improve codes and increase efficiency of work.

Moreover, this transparency makes sure that people can inspect and understand the origin of the data produced by the platforms. Users will have a deep insight of the data they will be working with.

For these reasons, transparency and open science will give more credibility and reliability to the project.

