---
author: '**Loïc Davadan**'
date: |
  21/05/2018 --- 20/08/2018
school: 'Bordeaux Sciences Agro'
institution: 'Centre de Recherches Agronomiques Wallon (CRA-W)'
address: 'Rue de Liroux 9, 5030 Gembloux, Belgique'
advisor: '*Internship supervisor* : Thomas Goossens'
supervisor: '*Supervisor* : Jean-Pierre Da Costa'
# Delete line 6 if you only have one advisor
department: 'U11'
# degree: 'Bachelor of Arts'
title: 'Internship report'
subtitle: 'AGROMET project : Investigating spatial interpolation of temperature using Multiple Linear Regression'
knit: "bookdown::render_book"
site: bookdown::bookdown_site
output: 
 thesisdown::thesis_pdf: default
#  thesisdown::thesis_gitbook: default 
# thesisdown::thesis_word: default
#  thesisdown::thesis_epub: default
# If you are creating a PDF you'll need to write your preliminary content here or
# use code similar to line 20 for the files.  If you are producing in a different
# format than PDF, you can delete or ignore lines 20-31 in this YAML header.
abstract: |
 `r if(knitr:::is_latex_output()) paste(readLines("00-abstract.Rmd"), collapse = '\n  ')`
# If you'd rather include the preliminary content in files instead of inline
# like below, use a command like that for the abstract above.  Note that a tab is 
# needed on the line after the |.
acknowledgements: | 
 `r if(knitr:::is_latex_output()) paste(readLines("00-acknowlegdements.Rmd"), collapse = '\n  ')`
preface: | 
 `r if(knitr:::is_latex_output()) paste(readLines("00-preface.Rmd"), collapse = '\n  ')`
abbreviations: | 
 `r if(knitr:::is_latex_output()) paste(readLines("00-abbreviations.Rmd"), collapse = '\n  ')` 
definitions: | 
 `r if(knitr:::is_latex_output()) paste(readLines("00-glossary.Rmd"), collapse = '\n  ')`  
bibliography: bib/thesis.bib
# Download your specific bibliography database file and refer to it in the line above.
csl: csl/apa.csl
# Download your specific csl file and refer to it in the line above.
index: true
lot: true
lof: true
#space_between_paragraphs: true
# Delete the # at the beginning of the previous line if you'd like
# to have a blank new line between each paragraph
#header-includes:
#- \usepackage{tikz}
---

<!--
Above is the YAML (YAML Ain't Markup Language) header that includes a lot of metadata used to produce the document.  Be careful with spacing in this header!

If you'd prefer to not include a Dedication, for example, simply delete lines 17 and 18 above or add a # before them to comment them out.  If you have other LaTeX packages you would like to include, delete the # before header-includes and list the packages after hyphens on new lines.

If you'd like to include a comment that won't be produced in your resulting file enclose it in a block like this.
-->

<!--
If you receive a duplicate label error after knitting, make sure to delete the index.Rmd file and then knit again.
-->

```{r include_packages, include = FALSE}
# This chunk ensures that the thesisdown package is
# installed and loaded. This thesisdown package includes
# the template files for the thesis.
if(!require(devtools))
  install.packages("devtools", repos = "http://cran.rstudio.com")
if(!require(thesisdown))
  devtools::install_github("ismayc/thesisdown")
library(thesisdown)
Sys.setenv(RSTUDIO_PDFLATEX = "latexmk")
```

<!-- You'll need to include the order that you'd like Rmd files to appear in the _bookdown.yml file for
PDF files and also delete the # before rmd_files: there.  You'll want to not include 00(two-hyphens)prelim.Rmd
and 00-abstract.Rmd since they are handled in the YAML above differently for the PDF version.
-->

<!-- The {.unnumbered} option here means that the introduction will be "Chapter 0." You can also use {-} for no numbers
on chapters.
-->

# Introduction {.unnumbered}

Use of pesticides and other crop protection products is a topical issue in an environmental and societal context. These products are increasingly criticized for their risks and impacts on human health and environment. Crop monitoring models are developed and their efficiency is well demonstrated. Acting at the right time in plots is inscreasingly possible thanks to these models. In Belgium, the Walloon agricultural resarch centre (CRA-W) is a research centre where a lot of issues are explored to bring solutions. 

From May 22nd to August 20th, I did an internship in the (CRA-W). I worked on the AGROMET project which is a project about agrometeorology where the aim is to provide a near real-time hourly gridded datasets of weather parameters at the resolution of 1 km² for the whole region of Wallonia characterized by a quality indicator. This project is led by the Farming Systems, Territory and Information Technologies Unit.

The internship has for objective to investigate a spatial interpolation of the temperature using multiple linar regression with the best combination of explanatory variables. 

First, the report will present the CRA-W, its organisation, the Unit where I worked and the project. Then, my workflow will be detailed in two parts : the data acquisition and the data analysis through the benchmark. Finally, the results will be interprated and discussed.

